apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-rtmp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nginx-rtmp.name" . }}
    helm.sh/chart: {{ include "nginx-rtmp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if eq .Values.service.type "Rancher-Proxy" }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  {{- if eq .Values.service.ui.type "Rancher-Proxy" }}
  type: ClusterIP
  {{- else }}
  type: {{ .Values.service.ui.type }}
  {{- end }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port.rtmp }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
    - port: {{ .Values.service.port.hls }}
      targetPort: hls
      protocol: TCP
      name: hls
  selector:
    app.kubernetes.io/name: {{ include "nginx-rtmp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
